<?php

use Faker\Generator as Faker;
use App\Models\{
  Members\MemberAddress,
  Members\Member,
  Locations\Country,
  Locations\State,
  Locations\City
};

/** @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(MemberAddress::class, function (Faker $faker) {
    
    $members = Member::whereNotExists(function($query) {
        $query->select(DB::raw(1))
            ->from('members_addresses_data')
            ->whereRaw('members.user_id = members_addresses_data.user_id');
    })->get()
        ->random(1);

    $country = Country::where('id', $members[0]->country_id)
        ->first();

    $state = State::where('country_id', $country->id)
        ->get()
        ->random(1);

    $city = City::where('country_id', $country->id)
        ->where('state_id', $state[0]->id)
        ->get()
        ->random(1);

    if($country->code_iso_2 == 'TW'){

        $faker->addProvider(new \Faker\Provider\zh_TW\Address($faker));

        $address = [
            "addresses" => [
                [
                    'title'=>'Permanent',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'市/縣',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->state(),
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'鄉鎮/市區',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->city(),
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'里/村',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'鄰',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'路/街',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->streetName(),
                            'required'=>false
                        ],
                        [
                            'index'=>6,
                            'label'=>'段',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomChineseNumber(),
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'巷',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>8,
                            'label'=>'弄',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>9,
                            'label'=>'號',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>10,
                            'label'=>'樓之',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>11,
                            'label'=>'室',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>12,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>'',
                            'required'=>true
                        ],
                        [
                            'index'=>13,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>14,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>15,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ],
                [
                    'title'=>'Correspondence',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'市/縣',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->state(),
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'鄉鎮/市區',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->city(),
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'里/村',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'鄰',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'路/街',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->streetName(),
                            'required'=>false
                        ],
                        [
                            'index'=>6,
                            'label'=>'段',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomChineseNumber(),
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'巷',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>8,
                            'label'=>'弄',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>9,
                            'label'=>'號',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>10,
                            'label'=>'樓之',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>11,
                            'label'=>'室',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>12,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>'',
                            'required'=>true
                        ],
                        [
                            'index'=>13,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>14,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>15,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ],
                [
                    'title'=>'Shipping 1',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'市/縣',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->state(),
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'鄉鎮/市區',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->city(),
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'里/村',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'鄰',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'路/街',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->streetName(),
                            'required'=>false
                        ],
                        [
                            'index'=>6,
                            'label'=>'段',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomChineseNumber(),
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'巷',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>8,
                            'label'=>'弄',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>9,
                            'label'=>'號',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>10,
                            'label'=>'樓之',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>11,
                            'label'=>'室',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>12,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>'',
                            'required'=>true
                        ],
                        [
                            'index'=>13,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>14,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>15,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ],
                [
                    'title'=>'Shipping 2',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'市/縣',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->state(),
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'鄉鎮/市區',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->city(),
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'里/村',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'鄰',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'路/街',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->streetName(),
                            'required'=>false
                        ],
                        [
                            'index'=>6,
                            'label'=>'段',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomChineseNumber(),
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'巷',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>8,
                            'label'=>'弄',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>9,
                            'label'=>'號',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>10,
                            'label'=>'樓之',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>$faker->randomNumber2(),
                            'required'=>false
                        ],
                        [
                            'index'=>11,
                            'label'=>'室',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>12,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>'',
                            'required'=>true
                        ],
                        [
                            'index'=>13,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>14,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>15,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ]
            ]
        ];
    }else{
        $address = [
            "addresses" => [
                [
                    'title'=>'Permanent',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'Address 1',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->address,
                            'min'=>6,
                            'helper'=>'Address must be greater then 6 character',
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'Address 2',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'Address 3',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'Address 4',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>$faker->postcode,
                            'required'=>true
                        ],
                        [
                            'index'=>6,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>8,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ],
                [
                    'title'=>'Correspondence',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'Address 1',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->address,
                            'min'=>6,
                            'helper'=>'Address must be greater then 6 character',
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'Address 2',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'Address 3',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'Address 4',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>$faker->postcode,
                            'required'=>true
                        ],
                        [
                            'index'=>6,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>8,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ],
                [
                    'title'=>'Shipping 1',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'Address 1',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->address,
                            'min'=>6,
                            'helper'=>'Address must be greater then 6 character',
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'Address 2',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'Address 3',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'Address 4',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>$faker->postcode,
                            'required'=>true
                        ],
                        [
                            'index'=>6,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>8,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ],
                [
                    'title'=>'Shipping 2',
                    'fields'=>[
                        [
                            'index'=>1,
                            'label'=>'Address 1',
                            'type'=>'input',
                            'order'=>1,
                            'value'=>$faker->address,
                            'min'=>6,
                            'helper'=>'Address must be greater then 6 character',
                            'required'=>true
                        ],
                        [
                            'index'=>2,
                            'label'=>'Address 2',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>3,
                            'label'=>'Address 3',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>4,
                            'label'=>'Address 4',
                            'type'=>'input',
                            'order'=>2,
                            'value'=>'',
                            'required'=>false
                        ],
                        [
                            'index'=>5,
                            'label'=>'postcode',
                            'type'=>'input',
                            'order'=>3,
                            'value'=>$faker->postcode,
                            'required'=>true
                        ],
                        [
                            'index'=>6,
                            'label'=>'city',
                            'type'=>'select',
                            'key'=>'cities',
                            'identifier'=>'cities',
                            'order'=>4,
                            'value'=>$city[0]->id,
                            'required'=>false
                        ],
                        [
                            'index'=>7,
                            'label'=>'country',
                            'type'=>'select',
                            'key'=>'countries',
                            'order'=>6,
                            'value'=>$country->id,
                            'required'=>true
                        ],
                        [
                            'index'=>8,
                            'label'=>'state',
                            'type'=>'select',
                            'key'=>'states',
                            'identifier'=>'states',
                            'trigger'=>'cities',
                            'order'=>5,
                            'value'=>$state[0]->id,
                            'required'=>false
                        ]
                    ]
                ]
            ]
        ];
    }

    return [
        'user_id' => $members[0]->user_id,
        'address_data' => json_encode($address["addresses"])
    ];
});
